"""esquema inicial

Revision ID: efa40f33710a
Revises: 
Create Date: 2026-07-25 22:36:59.992920
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector.sqlalchemy

revision: str = 'efa40f33710a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('specialty', sa.Enum('urologia', 'trauma', 'cardiologia', 'neurocirugia', 'otro', name='specialty', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qr_token', sa.String(length=32), nullable=False),
    sa.Column('cover_image_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publishstatus', native_enum=False, length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_models_code'), 'machine_models', ['code'], unique=True)
    op.create_index(op.f('ix_machine_models_qr_token'), 'machine_models', ['qr_token'], unique=True)
    op.create_index(op.f('ix_machine_models_specialty'), 'machine_models', ['specialty'], unique=False)
    op.create_index(op.f('ix_machine_models_status'), 'machine_models', ['status'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'google', 'grok', 'deepseek', name='llmproviderkey', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=8), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('last_check_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'label', name='uq_credential_provider_label')
    )
    op.create_index(op.f('ix_provider_credentials_is_active'), 'provider_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_provider_credentials_provider'), 'provider_credentials', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'trainee', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=160), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('source_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'processing', 'ready', 'failed', name='videostatus', native_enum=False, length=16), nullable=False),
    sa.Column('hls_master_key', sa.String(length=512), nullable=True),
    sa.Column('renditions', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_status'), 'video_assets', ['status'], unique=False)
    op.create_table('agent_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'google', 'grok', 'deepseek', name='llmproviderkey', native_enum=False, length=32), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt_extra', sa.Text(), nullable=True),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_top_k', sa.Integer(), nullable=False),
    sa.Column('tools_enabled', sa.Boolean(), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_is_active'), 'agent_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_configs_is_default'), 'agent_configs', ['is_default'], unique=False)
    op.create_index(op.f('ix_agent_configs_machine_model_id'), 'agent_configs', ['machine_model_id'], unique=False)
    op.create_table('tool_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('http_method', sa.String(length=8), nullable=False),
    sa.Column('url_template', sa.String(length=1024), nullable=False),
    sa.Column('parameters_schema', sa.JSON(), nullable=False),
    sa.Column('static_headers', sa.JSON(), nullable=False),
    sa.Column('auth_type', sa.Enum('none', 'bearer', 'api_key_header', 'basic', name='toolauthtype', native_enum=False, length=24), nullable=False),
    sa.Column('encrypted_auth_secret', sa.Text(), nullable=True),
    sa.Column('auth_secret_hint', sa.String(length=8), nullable=False),
    sa.Column('auth_header_name', sa.String(length=64), nullable=True),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_definitions_is_active'), 'tool_definitions', ['is_active'], unique=False)
    op.create_index(op.f('ix_tool_definitions_machine_model_id'), 'tool_definitions', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_name'), 'tool_definitions', ['name'], unique=True)
    op.create_table('training_modules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('requires_previous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publishstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_model_id', 'order_index', name='uq_module_order')
    )
    op.create_index(op.f('ix_training_modules_machine_model_id'), 'training_modules', ['machine_model_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_module_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'pdf', 'text', name='lessoncontenttype', native_enum=False, length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sa.Uuid(), nullable=True),
    sa.Column('document_key', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publishstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_module_id', 'order_index', name='uq_lesson_order')
    )
    op.create_index(op.f('ix_lessons_training_module_id'), 'lessons', ['training_module_id'], unique=False)
    op.create_index(op.f('ix_lessons_video_asset_id'), 'lessons', ['video_asset_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_module_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('grants_certificate', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publishstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_training_module_id'), 'quizzes', ['training_module_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('agent_config_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_machine_model_id'), 'conversations', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('manual_pdf', 'video_transcript', 'raw_text', name='documentsourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'failed', name='ingeststatus', native_enum=False, length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_lesson_id'), 'knowledge_documents', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_machine_model_id'), 'knowledge_documents', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('single_choice', 'multiple_choice', 'true_false', name='questiontype', native_enum=False, length=24), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_passed'), 'quiz_attempts', ['passed'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='progressstatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_position_seconds', sa.Float(), nullable=False),
    sa.Column('watched_percent', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_user_lesson')
    )
    op.create_index(op.f('ix_user_lesson_progress_lesson_id'), 'user_lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_lesson_progress_status'), 'user_lesson_progress', ['status'], unique=False)
    op.create_index(op.f('ix_user_lesson_progress_user_id'), 'user_lesson_progress', ['user_id'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('pdf_key', sa.String(length=512), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('holder_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('machine_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('score_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_attempt_id')
    )
    op.create_index(op.f('ix_certificates_code'), 'certificates', ['code'], unique=True)
    op.create_index(op.f('ix_certificates_machine_model_id'), 'certificates', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('machine_model_id', sa.Uuid(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(length=120), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_knowledge_chunks_is_global'), 'knowledge_chunks', ['is_global'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_machine_model_id'), 'knowledge_chunks', ['machine_model_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tool_definition_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['tool_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_conversation_id'), 'tool_invocations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_tool_definition_id'), 'tool_invocations', ['tool_definition_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_user_id'), 'tool_invocations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_invocations_user_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_tool_definition_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_conversation_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_chunks_machine_model_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_is_global'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_machine_model_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_code'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_user_lesson_progress_user_id'), table_name='user_lesson_progress')
    op.drop_index(op.f('ix_user_lesson_progress_status'), table_name='user_lesson_progress')
    op.drop_index(op.f('ix_user_lesson_progress_lesson_id'), table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_passed'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_machine_model_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_lesson_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_machine_model_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_quizzes_training_module_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_lessons_video_asset_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_training_module_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_training_modules_machine_model_id'), table_name='training_modules')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_tool_definitions_name'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_machine_model_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_is_active'), table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index(op.f('ix_agent_configs_machine_model_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_is_default'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_is_active'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_video_assets_status'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_provider_credentials_provider'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_is_active'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_machine_models_status'), table_name='machine_models')
    op.drop_index(op.f('ix_machine_models_specialty'), table_name='machine_models')
    op.drop_index(op.f('ix_machine_models_qr_token'), table_name='machine_models')
    op.drop_index(op.f('ix_machine_models_code'), table_name='machine_models')
    op.drop_table('machine_models')
    # ### end Alembic commands ###
