"""suggested questions en agent_configs

Revision ID: b66ef3b550e9
Revises: efa40f33710a
Create Date: 2026-07-28 00:51:51.926838
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b66ef3b550e9'
down_revision: str | None = 'efa40f33710a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Ajuste sobre el autogenerado: `nullable=False` sin default revienta si la tabla ya tiene
    # filas (el agente por defecto del seed existe). El server_default puebla las existentes;
    # las nuevas lo ponen desde la aplicación.
    op.add_column(
        'agent_configs',
        sa.Column('suggested_questions', sa.JSON(), nullable=False, server_default='[]'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'suggested_questions')
    # ### end Alembic commands ###
